"""The boundary with the loosely typed surfaces of LangChain and LangGraph.

LangChain types a request's runtime context, its structured response, its
state, a hook's state update and a stream writer's payload as `Any`. Those
types are named here, once, so every other module works with the library's own
precise types. This is also the only module that touches LangChain's callback
managers, through which the monitor's spans reach every tracer.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator, Awaitable, Callable, Iterator, Mapping, Sequence
from contextlib import asynccontextmanager, contextmanager
from contextvars import ContextVar
from dataclasses import dataclass, field, replace
from typing import Any, Literal, NotRequired, TypedDict, cast
from uuid import UUID

from langchain.agents.middleware.types import (
    AgentMiddleware,
    ModelRequest,
    ModelResponse,
    ToolCallRequest,
)
from langchain.tools import ToolRuntime
from langchain_core.callbacks import AsyncCallbackManager, BaseCallbackManager, CallbackManager
from langchain_core.messages import AnyMessage, BaseMessage, ToolMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.runnables.config import ensure_config, patch_config, var_child_runnable_config
from langgraph.constants import TAG_NOSTREAM
from langgraph.runtime import Runtime
from langgraph.types import Command
from pydantic import TypeAdapter, ValidationError

from langchain_sync_monitors.contracts import Delegation, SampleRecord, StepRecord
from langchain_sync_monitors.errors import ConfigurationError

logger = logging.getLogger(__name__)

type TraceValue = str | int | float | bool | Sequence[TraceValue] | Mapping[str, TraceValue] | None
"""A plain value a monitor span carries in its inputs, outputs or metadata."""

type TraceValues = Mapping[str, TraceValue]
"""A span's inputs, outputs or metadata: plain values by name."""

type AgentContext = Any
"""The runtime context of the agent a monitor sits in, whatever its schema."""

type StructuredOutput = Any
"""The structured response of the agent a monitor sits in, whatever its schema."""

type AgentModelRequest = ModelRequest[AgentContext]
"""A model request of any agent, whatever its context schema."""

type AgentModelResponse = ModelResponse[StructuredOutput]
"""A model response of any agent, whatever its structured response schema."""

type ModelCallHandler = Callable[[AgentModelRequest], AgentModelResponse]
"""The callback LangChain passes to `wrap_model_call` to run the rest of the stack."""

type AsyncModelCallHandler = Callable[[AgentModelRequest], Awaitable[AgentModelResponse]]
"""The callback LangChain passes to `awrap_model_call` to run the rest of the stack."""

type AnyAgentMiddleware = AgentMiddleware[Any, AgentContext, StructuredOutput]
"""A middleware of any state, context and response schema, as `create_agent` accepts."""

type SubagentMiddleware = AgentMiddleware
"""A middleware as Deep Agents types a subagent's `middleware` list, with LangChain's defaults."""

type AgentRuntime = Runtime[AgentContext]
"""The runtime LangChain passes to a middleware's node hooks, whatever the context schema."""

type AgentStateUpdate = dict[str, Any]
"""A state update a middleware's node hook returns, which LangChain types by key only."""

type ToolCallResult = ToolMessage | Command[Any]
"""What a tool call returns to the agent: a tool message, or a command with any update."""

type ToolCallHandler = Callable[[ToolCallRequest], ToolCallResult]
"""The callback LangChain passes to `wrap_tool_call` to run the rest of the stack."""

type AsyncToolCallHandler = Callable[[ToolCallRequest], Awaitable[ToolCallResult]]
"""The callback LangChain passes to `awrap_tool_call` to run the rest of the stack."""

MONITOR_LOG_KEY = "monitor_log"
"""The state key that holds the step records of every monitor in the run."""

MONITOR_DELEGATION_KEY = "monitor_delegation"
"""The state key through which a monitored agent hands a subagent its `Delegation`."""

DELEGATION_ADAPTER = TypeAdapter(Delegation)
"""Validates a `Delegation` read from the state, where an agent's input can also put one."""

span_labels: ContextVar[TraceValues | None] = ContextVar("monitor_span_labels", default=None)
"""The metadata keys every monitor span opened in the current step carries, if any."""


@dataclass(frozen=True, slots=True, kw_only=True)
class TraceSpan:
    """A named run the monitor opens in the agent's trace.

    `tags` and `metadata` belong to this run alone: the model calls made inside
    it keep exactly the tags and metadata LangChain gives them. `run_id` is
    generated by LangChain unless it is given.
    """

    name: str
    inputs: TraceValues = field(default_factory=dict)
    metadata: TraceValues = field(default_factory=dict)
    tags: Sequence[str] = ()
    run_id: UUID | None = None


@dataclass(slots=True, kw_only=True)
class TracedRun:
    """What a traced block reports before its span ends.

    `outputs` end the span. `inputs_at_end`, when set, replace the inputs the
    span started with, for inputs that exist only once the block has run;
    LangSmith, Langfuse and `astream_events` all take inputs at the end
    [@langchain2026].
    """

    outputs: TraceValues = field(default_factory=dict)
    inputs_at_end: TraceValues | None = None

    def build_end_arguments(self) -> dict[str, dict[str, TraceValue]]:
        """Return the keyword arguments that end the span: the late inputs, when there are any."""
        return {} if self.inputs_at_end is None else {"inputs": dict(self.inputs_at_end)}


class MonitorStepEvent(TypedDict):
    """The event a monitor writes to `stream_mode="custom"` once per committed step.

    It follows the typed events Deep Agents' `RubricMiddleware` writes to the
    same stream [@deepagents2026].
    """

    type: Literal["monitor_step"]
    record: StepRecord


class MonitorStepFailedEvent(TypedDict):
    """The event a monitor writes to `stream_mode="custom"` when a step fails uncommitted.

    A call inside the step raised before the protocol decided, so no record
    reaches `monitor_log`. The event keeps what the monitor had judged by then:
    `samples` holds each judged sample, none of them executed, and `error`
    names the exception, which the middleware raises again after the event.
    """

    type: Literal["monitor_step_failed"]
    agent: str
    monitor: str
    step_number: int
    error: str
    samples: list[SampleRecord]
    delegation_id: NotRequired[str]


type MonitorStreamEvent = MonitorStepEvent | MonitorStepFailedEvent
"""Every event a monitor writes to `stream_mode="custom"`."""


def read_monitor_log(state: Mapping[str, object]) -> list[StepRecord]:
    """Return the step records in an agent state, or an empty list when there are none."""
    records = state.get(MONITOR_LOG_KEY)
    if not isinstance(records, list):
        return []
    return cast("list[StepRecord]", records)


def read_delegation(state: object) -> Delegation | None:
    """Return the delegation a subagent was started with, or None in an agent started directly.

    A tool request's state is untyped in LangChain, and may be something other
    than a mapping, which holds no delegation. The key is part of every
    monitored agent's input, so whoever invokes the agent can set it, and the
    value is validated before it is used. A value that is not a `Delegation`
    with non-negative block counts raises `ConfigurationError`. Ignoring it
    would not do: a subagent would count from its own log alone and so reset
    the thread's total, and a negative count would lift the total altogether.
    """
    if not isinstance(state, Mapping):
        return None
    value = state.get(MONITOR_DELEGATION_KEY)
    if value is None:
        return None
    try:
        return DELEGATION_ADAPTER.validate_python(value, strict=True)
    except ValidationError as error:
        message = (
            f"{MONITOR_DELEGATION_KEY} must be a Delegation with non-negative block counts. "
            "Leave it out of an agent's input: the monitor sets it for each subagent it starts."
        )
        raise ConfigurationError(message) from error


def build_tool_request_with_delegation(
    request: ToolCallRequest,
    *,
    delegation: Delegation,
) -> ToolCallRequest:
    """Return a copy of the tool request whose state holds the delegation.

    A tool reads the state from its injected runtime, not from the request, so
    both are replaced [@langgraph2026]. Deep Agents' `task` tool passes that
    state, less a few keys, to the subagent it starts, and the subagent's
    state schema keeps the key out of its output, as Deep Agents does for its
    own forked-context flag [@deepagents2026]. A request whose state is not a
    mapping, or that runs outside a graph, is returned unchanged.
    """
    runtime = cast("ToolRuntime | None", request.runtime)
    if not isinstance(request.state, Mapping) or runtime is None:
        return request
    state = {**request.state, MONITOR_DELEGATION_KEY: delegation}
    return replace(request, state=state, runtime=replace(runtime, state=state))


def build_request_with_messages(
    request: AgentModelRequest,
    *,
    messages: Sequence[BaseMessage],
) -> AgentModelRequest:
    """Return a copy of the request that sends these messages to the model.

    LangChain types a request's messages as its `AnyMessage` union, which every
    concrete message the library builds belongs to.
    """
    return request.override(messages=cast("list[AnyMessage]", list(messages)))


def append_subagent_middleware(
    existing: Sequence[SubagentMiddleware],
    *,
    middleware: AnyAgentMiddleware,
) -> list[SubagentMiddleware]:
    """Return a subagent's middleware list with one more middleware at the end.

    Deep Agents declares the list with LangChain's default type parameters, and
    generic middleware types do not convert to one another, although every
    middleware fits the list at run time [@deepagents2026].
    """
    return [*existing, cast("SubagentMiddleware", middleware)]


def write_stream_event(request: AgentModelRequest, *, event: MonitorStreamEvent) -> None:
    """Write the event to `stream_mode="custom"`, if the request runs inside a graph.

    A request built outside a graph has no runtime, and so no writer. A writer
    that fails must not undo a step that is already decided, so its error is
    logged and dropped.
    """
    writer = getattr(request.runtime, "stream_writer", None)
    if writer is None:
        return
    try:
        writer(event)
    except Exception:
        logger.exception("The stream writer failed on a monitor step event; the step stands.")


@contextmanager
def hide_model_calls_from_message_stream() -> Iterator[None]:
    """Keep every model call made inside the block out of `stream_mode="messages"`.

    LangGraph's message stream skips a model call tagged `nostream`, and still
    streams the messages a node returns once the node finishes [@langgraph2026].
    The tag goes on the config that calls inside the block inherit, so it
    reaches the agent's samples, the trusted model's step and the monitor's own
    calls alike, including calls in tasks started inside the block. A call made
    with its own `tags` replaces the inherited ones and streams again.
    """
    config = var_child_runnable_config.get() or RunnableConfig()
    hidden_config: RunnableConfig = {**config, "tags": [*config.get("tags", []), TAG_NOSTREAM]}
    token = var_child_runnable_config.set(hidden_config)
    try:
        yield
    finally:
        var_child_runnable_config.reset(token)


@contextmanager
def label_monitor_spans(labels: TraceValues) -> Iterator[None]:
    """Give every span a monitor opens inside the block these metadata keys as well.

    The labels name the step, so a span deep inside a monitor, such as a
    decision model's request, can be traced back to its step. They sit in a
    context variable, which the tasks started inside the block copy, and not
    in the metadata LangChain passes down, so no model call inside the block
    carries them.
    """
    token = span_labels.set(labels)
    try:
        yield
    finally:
        span_labels.reset(token)


def build_span_manager[ManagerT: (CallbackManager, AsyncCallbackManager)](
    config: RunnableConfig,
    *,
    span: TraceSpan,
    manager_class: type[ManagerT],
) -> ManagerT | None:
    """Return the callback manager that starts the span, or None when no handler listens.

    Inside a graph node, the config holds the node's own callback manager, and
    the span's manager is built from it, so the span nests under the running
    node for every handler. `CallbackManager.configure` would build it too, but
    with LangSmith tracing on it re-parents the span under the LangSmith-only
    run in which `create_agent` wraps each middleware hook, a run that Langfuse
    and every other handler never see [@langchain2026; @langfuse2026].
    Outside a graph, where the callbacks are a list or nothing, the manager is
    configured from the config as LangChain configures any run.

    The span takes the handlers and parent of that manager, and the tags and
    metadata it passes on, as LangChain's `get_child` does; a tag meant for
    the node's own next run, such as `seq:step:1`, stays behind. The node's
    manager is never changed, and the span's own tags, metadata and labels are
    not inherited by the calls inside it.
    """
    callbacks = config.get("callbacks")
    source = (
        callbacks
        if isinstance(callbacks, BaseCallbackManager)
        else CallbackManager.configure(
            inheritable_callbacks=callbacks,
            inheritable_metadata=config.get("metadata"),
        )
    )
    if not source.handlers:
        return None
    callback_manager = manager_class(
        handlers=list(source.handlers),
        inheritable_handlers=list(source.inheritable_handlers),
        parent_run_id=source.parent_run_id,
        tags=list(source.inheritable_tags),
        inheritable_tags=list(source.inheritable_tags),
        metadata=dict(source.inheritable_metadata),
        inheritable_metadata=dict(source.inheritable_metadata),
    )
    callback_manager.add_tags(list(span.tags), inherit=False)
    callback_manager.add_metadata({**(span_labels.get() or {}), **span.metadata}, inherit=False)
    return callback_manager


@contextmanager
def open_traced_run_sync(span: TraceSpan) -> Iterator[TracedRun]:
    """Open the span under the running node, for `invoke()`; model calls in the block nest in it.

    With no callback handler attached nothing is opened, and the block runs as
    it would without the span. Otherwise the span starts with its inputs, and
    the calls made inside the block become its children through the config
    they inherit, the way `hide_model_calls_from_message_stream` sets it. The
    span ends with the outputs the block reports, or with the exception that
    leaves the block, cancellation included, as LangChain ends a runnable's run
    [@langchain2026]. A tracer that fails is logged by LangChain and never
    fails the step.
    """
    config = ensure_config()
    callback_manager = build_span_manager(config, span=span, manager_class=CallbackManager)
    traced_run = TracedRun()
    if callback_manager is None:
        yield traced_run
        return
    run_manager = callback_manager.on_chain_start(
        None, dict(span.inputs), run_id=span.run_id, name=span.name
    )
    token = var_child_runnable_config.set(patch_config(config, callbacks=run_manager.get_child()))
    try:
        yield traced_run
    except BaseException as error:
        run_manager.on_chain_error(error, **traced_run.build_end_arguments())
        raise
    else:
        run_manager.on_chain_end(dict(traced_run.outputs), **traced_run.build_end_arguments())
    finally:
        var_child_runnable_config.reset(token)


@asynccontextmanager
async def open_traced_run(span: TraceSpan) -> AsyncIterator[TracedRun]:
    """Open the span under the running node, for `ainvoke()`; model calls in the block nest in it.

    It behaves as `open_traced_run_sync`, through LangChain's async callback
    manager, whose handlers must not run on another event loop. The span ends
    even when the task is cancelled, since LangChain shields the callbacks
    that end a run [@langchain2026].
    """
    config = ensure_config()
    callback_manager = build_span_manager(config, span=span, manager_class=AsyncCallbackManager)
    traced_run = TracedRun()
    if callback_manager is None:
        yield traced_run
        return
    run_manager = await callback_manager.on_chain_start(
        None, dict(span.inputs), run_id=span.run_id, name=span.name
    )
    token = var_child_runnable_config.set(patch_config(config, callbacks=run_manager.get_child()))
    try:
        yield traced_run
    except BaseException as error:
        await run_manager.on_chain_error(error, **traced_run.build_end_arguments())
        raise
    else:
        await run_manager.on_chain_end(dict(traced_run.outputs), **traced_run.build_end_arguments())
    finally:
        var_child_runnable_config.reset(token)
